name: PyTest
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python: ['3.7', '3.11', 'pypy-3.7', 'pypy-3.9']
        dbms: ['mysql-5', 'mysql-8']
    name: ${{ matrix.python }} with ${{ matrix.dbms }}
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Run database server in docker
        run: |
          docker-compose up -d ${{ matrix.dbms }}
          echo "wait mysql server"
        
          while :
          do
            if mysql -h 127.0.0.1 --user=root --execute "SELECT version();" 2>&1 >/dev/null && mysql -h 127.0.0.1 --port=3307  --user=root --execute "SELECT version();" 2>&1 >/dev/null; then
              break
            fi
            sleep 1
          done
          
          echo "run pytest"

      - name: Install dependencies
        run: |
          pip install .
          pip install pytest

      - name: Run test suite
        run: |
          pytest -k "not test_no_trailing_rotate_event and not test_end_log_pos" --dbms=${{ matrix.dbms }}

